version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ['*']
    open-pull-requests-limit: 5
    labels: [dependencies]

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm-development:
        dependency-type: development
      npm-production:
        dependency-type: production
    open-pull-requests-limit: 5
    labels: [dependencies]
